version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "02:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.1.0
  - dependency-name: ember-template-lint
    versions:
    - 3.0.1
    - 3.1.1
  commit-message:
    prefix: ""
